from docx import Document
from docx2pdf import convert

company = 'Apple'
where_you_found_job = 'LinkedIn'
role = 'Engineering Management'
reason_you_want_job = 'I am eager to bring my creativity and love of learning to a company whose products and mission I deeply believe in.'
cover_letter = f"Rhett Reisman {company} {role}"
document = Document()

p_explanation = document.add_paragraph('This cover letter has been generated by my ')
p_explanation.add_run('Notion Cover Letter Python Script').bold = True

p_source_code = document.add_paragraph('Source code is available here: https://github.com/rhettre/NotionCoverLetterGenerator')

p_hello = document.add_paragraph(f'Hello {company} Team,')

p_where_you_saw_job = document.add_paragraph(f'I saw your job posting on {where_you_found_job} and it sounds like an interesting opportunity!')

p_background = document.add_paragraph(f'A little background on me: I grew up loving math and technology which led me to a degree in Computer Science and Business from Lehigh University. This led to my first job in insurance consulting where I have worked on multi-million dollar software implementations first as a developer and now as a project manager.')

p_why = document.add_paragraph(f'Throughout my career I’ve taken on more and more responsibility and I see this {role} role at {company} as a great next step and huge opportunity. {reason_you_want_job}')

p_any_questions = document.add_paragraph(f'Please let me know if I can answer any questions for you, I’d love to learn more about the position and your work at {company}')

p_sign_off = document.add_paragraph('Cheers,')

p_signature = document.add_paragraph('Rhett Reisman')

document.save(f'{cover_letter}.docx')

convert(f"{cover_letter}.docx", f"{cover_letter}.pdf")
